### ISSUE TITLE
Fake Fullscreen

### ISSUE THREAD

**Issue by mrcnpp** [oleerik/hex-linux-launcher#11]
HI ,
Thanks for making a native hex client :)
Using it the fullscreen mode is a "fake" because the Title bar does not disapear and the information showed at the bottom how the page are inaccesible.
In case that can help you i'm using ubuntu budgie 17.04 
![fullscren](https://user-images.githubusercontent.com/8047343/35443559-d0aea656-02ab-11e8-854f-7e45bec42057.png)

**Comment by lillelilje** [comment]
Hey! This is because proper fullscreen doesn't work in the unity version that HEX is currently using.
Sadly there isn't much I can do about it. This is just a community-made launcher.

What I can say though is, try to find a way to force the application to go fullscreen (rightclick the titlebar and see if you have any options.
If not, click the cog wheels in the top right and reduce the window size a bit.

You can also choose "fullscreen" there, but be warned: It's glitchy and you'll likely lose the ability to control the game every now and then.

From the developers:
The client does not accept mouse input when started in fullscreen mode. Fullscreen mode works when switched into from Windowed mode mid-session

**Comment by mrcnpp** [comment]
Thanks forum the Quick answer i'll try tour ideas

Il 26 gen 2018 15:33, "fosspill" <notifications@github.com> ha scritto:

**Comment by lillelilje** [comment]
No problem, I'll close to issue but feel free to keep commenting here and I'll try to help as much as I can!
